
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EliteMart.EF
{

using System;
    using System.Collections.Generic;
    
public partial class ChiTietXuat
{

    public int MaChiTietXuat { get; set; }

    public Nullable<int> MaPhieuXuat { get; set; }

    public Nullable<int> MaHangHoa { get; set; }

    public Nullable<int> SoLuong { get; set; }

    public Nullable<double> DonGia { get; set; }



    public virtual HangHoa HangHoa { get; set; }

    public virtual PhieuXuatHang PhieuXuatHang { get; set; }

}

}
