
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EliteMart.EF
{

using System;
    using System.Collections.Generic;
    
public partial class ChiTietNhap
{

    public int MaChiTietNhap { get; set; }

    public Nullable<int> MaPhieuNhap { get; set; }

    public Nullable<int> MaHangHoa { get; set; }

    public Nullable<int> SoLuong { get; set; }

    public Nullable<double> DonGia { get; set; }



    public virtual HangHoa HangHoa { get; set; }

    public virtual PhieuNhapHang PhieuNhapHang { get; set; }

}

}
