
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EliteMart.EF
{

using System;
    using System.Collections.Generic;
    
public partial class HoaDon
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public HoaDon()
    {

        this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();

    }


    public int MaHoaDon { get; set; }

    public string NhanVien { get; set; }

    public Nullable<System.DateTime> NgayLap { get; set; }

    public string HoTen { get; set; }

    public Nullable<bool> GioiTinh { get; set; }

    public Nullable<System.DateTime> NgaySinh { get; set; }

    public string DiaChi { get; set; }

    public string QueQuan { get; set; }

    public string SoDienThoai { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }

    public virtual TaiKhoan TaiKhoan { get; set; }

}

}
