
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EliteMart.EF
{

using System;
    using System.Collections.Generic;
    
public partial class PhieuXuatHang
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PhieuXuatHang()
    {

        this.ChiTietXuats = new HashSet<ChiTietXuat>();

    }


    public int MaPhieuXuatHang { get; set; }

    public string NguoiQuanLy { get; set; }

    public Nullable<int> MaKhachHang { get; set; }

    public Nullable<System.DateTime> NgayXuat { get; set; }

    public Nullable<System.DateTime> NgayGiaoHang { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ChiTietXuat> ChiTietXuats { get; set; }

    public virtual KhachHang KhachHang { get; set; }

    public virtual TaiKhoan TaiKhoan { get; set; }

}

}
