
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EliteMart.EF
{

using System;
    using System.Collections.Generic;
    
public partial class TaiKhoan
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TaiKhoan()
    {

        this.HoaDons = new HashSet<HoaDon>();

        this.PhieuXuatHangs = new HashSet<PhieuXuatHang>();

        this.PhieuNhapHangs = new HashSet<PhieuNhapHang>();

    }


    public string TenDangNhap { get; set; }

    public string MatKhau { get; set; }

    public string HoTen { get; set; }

    public Nullable<bool> GioiTinh { get; set; }

    public Nullable<System.DateTime> NgaySinh { get; set; }

    public string DiaChi { get; set; }

    public string QueQuan { get; set; }

    public string SoDienThoai { get; set; }

    public Nullable<int> MaLoaiTaiKhoan { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HoaDon> HoaDons { get; set; }

    public virtual LoaiTaiKhoan LoaiTaiKhoan { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PhieuXuatHang> PhieuXuatHangs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PhieuNhapHang> PhieuNhapHangs { get; set; }

}

}
