using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace EliteMart.UC
{
    public partial class KhachHangUC : UserControl
    {
        public KhachHangUC()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            EliteMart.EF.AppDB dbContext = new EliteMart.EF.AppDB();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.KhachHangs.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    khachHangsBindingSource.DataSource = dbContext.KhachHangs.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }
    }
}
